version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs
      POSTGRES_INITDB_ARGS: '--encondig=UTF-8'
      TZ: 'Asia/Tokyo'
    restart: always
