version: '3'

services:
  postgres:
    image: postgres:13
    container_name: postgres
    ports:
      - 5432:5432
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: root
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nestjs
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
      TZ: 'Asia/Tokyo'
